from __future__ import annotations

PUBLIC_KNOWLEDGE_SEED: tuple[dict, ...] = (
    {
        "record_id": "ma_ccc_regulator",
        "state": "MA",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Massachusetts Cannabis Control Commission",
        "summary": "Primary Massachusetts regulator for adult-use and medical cannabis licensing, operations, guidance, and enforcement.",
        "source_url": "https://masscannabiscontrol.com/",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("massachusetts", "ccc", "compliance", "license", "medical", "adult-use"),
        "update_cadence": "ongoing",
        "notes": "Use as primary grounding for Massachusetts regulatory questions.",
    },
    {
        "record_id": "ma_metrc_contract_2025",
        "state": "MA",
        "domain": "tracking",
        "topic": "seed_to_sale",
        "title": "Massachusetts Metrc Track-and-Trace Contract",
        "summary": "Massachusetts renewed Metrc in 2025 to continue statewide cannabis supply-chain tracking and traceability.",
        "source_url": "https://www.metrc.com/news/metrc-extends-track-and-trace-partnership-through-new-contract-with-commonwealth-of-massachusetts/",
        "source_type": "tracking_vendor",
        "trust_level": "high",
        "keywords": ("metrc", "tracking", "massachusetts", "manifest", "inventory", "traceability"),
        "update_cadence": "2025 contract",
        "notes": "Useful for chain-of-custody and seed-to-sale discussions.",
    },
    {
        "record_id": "ny_ocm_regulator",
        "state": "NY",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "New York Office of Cannabis Management",
        "summary": "Primary New York regulator for adult-use, medical, cannabinoid hemp, and licensing guidance.",
        "source_url": "https://cannabis.ny.gov/",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("new york", "ocm", "license", "packaging", "medical", "adult-use"),
        "update_cadence": "ongoing",
        "notes": "Primary authority for New York state program questions.",
    },
    {
        "record_id": "ny_plma_2025",
        "state": "NY",
        "domain": "compliance",
        "topic": "packaging_labeling_marketing",
        "title": "New York PLMA Rules",
        "summary": "New York adopted updated packaging, labeling, marketing, and advertising requirements effective in late 2025 with phased compliance in 2026.",
        "source_url": "https://cannabis.ny.gov/plma",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("plma", "packaging", "labeling", "marketing", "new york"),
        "update_cadence": "2025 update",
        "notes": "Important for retail packaging and product launch review.",
    },
    {
        "record_id": "nj_crc_regulator",
        "state": "NJ",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "New Jersey Cannabis Regulatory Commission",
        "summary": "Primary New Jersey regulator for medicinal and adult-use cannabis licensing, rules, and enforcement.",
        "source_url": "https://www.nj.gov/cannabis/",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("new jersey", "crc", "adult-use", "medical", "compliance", "rules"),
        "update_cadence": "ongoing",
        "notes": "Primary New Jersey compliance source.",
    },
    {
        "record_id": "nj_metrc_tracking",
        "state": "NJ",
        "domain": "tracking",
        "topic": "seed_to_sale",
        "title": "New Jersey Metrc Track-and-Trace Launch",
        "summary": "New Jersey selected Metrc for state cannabis track-and-trace to support medical and adult-use regulation.",
        "source_url": "https://www.metrc.com/news/metrc-announces-new-track-and-trace-contract-with-new-jersey/",
        "source_type": "tracking_vendor",
        "trust_level": "high",
        "keywords": ("new jersey", "metrc", "tracking", "traceability", "manifest"),
        "update_cadence": "ongoing",
        "notes": "Use when discussing New Jersey package tracking and operational traceability.",
    },
    {
        "record_id": "me_ocp_regulator",
        "state": "ME",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Maine Office of Cannabis Policy",
        "summary": "Primary Maine source for adult-use licensing, policy, compliance, and open data resources.",
        "source_url": "https://www.maine.gov/dafs/ocp/cannabis",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("maine", "ocp", "policy", "license", "compliance"),
        "update_cadence": "ongoing",
        "notes": "Primary Maine compliance and licensing authority.",
    },
    {
        "record_id": "me_open_data_sales",
        "state": "ME",
        "domain": "market",
        "topic": "open_data",
        "title": "Maine Cannabis Open Data",
        "summary": "Maine publishes open cannabis data including sales, testing, and license information that can inform market context.",
        "source_url": "https://www.maine.gov/dafs/ocp/open-data",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("maine", "sales", "open data", "testing", "market", "license"),
        "update_cadence": "monthly",
        "notes": "Useful for building market context and testing trend references.",
    },
    {
        "record_id": "pa_mmj_program",
        "state": "PA",
        "domain": "compliance",
        "topic": "medical_program",
        "title": "Pennsylvania Medical Marijuana Program",
        "summary": "Pennsylvania regulates cannabis through its medical marijuana program with licensing, patient registration, and oversight requirements.",
        "source_url": "https://www.pa.gov/agencies/health/programs/medical-marijuana.html",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("pennsylvania", "medical", "program", "patient", "license"),
        "update_cadence": "ongoing",
        "notes": "Pennsylvania remains medical-only under this source context.",
    },
    {
        "record_id": "mi_cra_regulator",
        "state": "MI",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Michigan Cannabis Regulatory Agency",
        "summary": "Michigan CRA oversees adult-use establishments, medical facilities, hemp processing, enforcement, and statewide marijuana monitoring resources.",
        "source_url": "https://www.michigan.gov/cra",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("michigan", "cra", "adult-use", "medical", "hemp", "metrc"),
        "update_cadence": "ongoing",
        "notes": "Use for Michigan licensing, enforcement, and monitoring questions.",
    },
    {
        "record_id": "md_cannabis_admin",
        "state": "MD",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Maryland Cannabis Administration",
        "summary": "Maryland Cannabis Administration regulates cultivation, manufacturing, testing, and distribution for medical and adult-use markets.",
        "source_url": "https://cannabis.maryland.gov/pages/cannabisfaq.aspx",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("maryland", "mca", "adult-use", "medical", "testing", "distribution"),
        "update_cadence": "ongoing",
        "notes": "Useful for possession, product category, and agency authority references.",
    },
    {
        "record_id": "oh_dcc_2026",
        "state": "OH",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Ohio Division of Cannabis Control",
        "summary": "Ohio law establishes the Division of Cannabis Control to administer cultivator, processor, dispensary, laboratory, and patient program licensing.",
        "source_url": "https://codes.ohio.gov/ohio-revised-code/section-3796.02/3-20-2026",
        "source_type": "statute",
        "trust_level": "high",
        "keywords": ("ohio", "division of cannabis control", "processor", "lab", "dispensary"),
        "update_cadence": "2026 statutory update",
        "notes": "Strong statutory reference for Ohio program authority.",
    },
    {
        "record_id": "ct_ombudsman",
        "state": "CT",
        "domain": "compliance",
        "topic": "medical_program_support",
        "title": "Connecticut Office of the Cannabis Ombudsman",
        "summary": "Connecticut operates an Office of the Cannabis Ombudsman focused on patient experience, research, and support for the medical marijuana program.",
        "source_url": "https://portal.ct.gov/cannabisombudsman",
        "source_type": "state_office",
        "trust_level": "high",
        "keywords": ("connecticut", "ombudsman", "medical", "patient", "program"),
        "update_cadence": "ongoing",
        "notes": "Useful for Connecticut patient-program context rather than broad licensing authority.",
    },
    {
        "record_id": "metrc_about_tracking",
        "state": None,
        "domain": "tracking",
        "topic": "traceability",
        "title": "Metrc Track-and-Trace Overview",
        "summary": "Metrc describes its RFID-enabled regulatory platform as providing end-to-end supply-chain visibility for cannabis tracking, testing, transport, and sale.",
        "source_url": "https://www.metrc.com/about/",
        "source_type": "tracking_vendor",
        "trust_level": "medium",
        "keywords": ("metrc", "rfid", "traceability", "tracking", "transport", "testing"),
        "update_cadence": "ongoing",
        "notes": "Good background source for seed-to-sale system capabilities.",
    },
    {
        "record_id": "scco2_terpenes_pressure_temp",
        "state": None,
        "domain": "extraction_science",
        "topic": "supercritical_co2_selectivity",
        "title": "Supercritical CO2 extraction pressure and temperature effects",
        "summary": "Published research shows extraction yield and composition change materially with pressure and temperature, with lower pressures favoring some terpenes and higher pressures favoring cannabinoids.",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9502342/",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("supercritical co2", "pressure", "temperature", "terpenes", "cannabinoids", "selectivity"),
        "update_cadence": "stable",
        "notes": "Use for extraction-condition reasoning and terpene vs cannabinoid targeting.",
    },
    {
        "record_id": "scco2_fractionation_pressures",
        "state": None,
        "domain": "extraction_science",
        "topic": "terpene_fractionation",
        "title": "SC-CO2 terpene-rich vs CBD-rich fractionation",
        "summary": "Systematic work found low pressures around 90–110 bar favored terpene recovery while higher pressures around 200–300 bar favored cannabidiol-rich fractions.",
        "source_url": "https://www.sciencedirect.com/science/article/pii/S0926669022008780",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("sc-co2", "fractionation", "terpene", "cbd", "pressure", "bar"),
        "update_cadence": "stable",
        "notes": "Useful for rule-based extraction suggestions around fractionation strategy.",
    },
    {
        "record_id": "decarb_review_filer",
        "state": None,
        "domain": "extraction_science",
        "topic": "decarboxylation",
        "title": "Acidic cannabinoid decarboxylation review",
        "summary": "A peer-reviewed review explains how acidic cannabinoids convert to neutral cannabinoids and why controlling decarboxylation matters in harvesting, storage, and processing.",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/34550791/",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("decarboxylation", "thca", "cbda", "neutral cannabinoids", "kinetics"),
        "update_cadence": "stable",
        "notes": "Use for decarb_conversion_note and acid-to-neutral reasoning.",
    },
    {
        "record_id": "decarb_kinetics_wang",
        "state": None,
        "domain": "extraction_science",
        "topic": "decarboxylation_kinetics",
        "title": "Decarboxylation kinetics across temperature",
        "summary": "Controlled studies reported first-order or pseudo-first-order decarboxylation behavior across 80°C to 145°C and showed THCA-A decarboxylated faster than CBDA and CBGA.",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/28861498/",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("decarboxylation", "kinetics", "temperature", "thca", "cbda", "cbga"),
        "update_cadence": "stable",
        "notes": "Useful for time-temperature warnings in decarb and post-processing.",
    },
    {
        "record_id": "ple_conversion_temps",
        "state": None,
        "domain": "extraction_science",
        "topic": "thermochemical_conversion",
        "title": "Thermo-chemical conversion temperatures for cannabinoid acids",
        "summary": "Pressurized liquid extraction research found different cannabinoids reached optimal conversion at different temperatures, including THC around 120°C for 6 minutes and CBD/CBG-related compounds around 140°C.",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/34465400/",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("temperature", "conversion", "thc", "cbd", "cbg", "decarb"),
        "update_cadence": "stable",
        "notes": "Useful when recommending thermal-conversion windows and overprocessing risk.",
    },
)
