from __future__ import annotations

PUBLIC_KNOWLEDGE_RECORDS_V2: tuple[dict, ...] = (
    {
        "record_id": "ma_ccc_regulator",
        "state": "MA",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Massachusetts Cannabis Control Commission",
        "summary": "Primary Massachusetts regulator for adult-use and medical cannabis licensing, operations, guidance, and enforcement.",
        "source_url": "https://masscannabiscontrol.com/",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("massachusetts", "ccc", "compliance", "license", "medical", "adult-use"),
        "update_cadence": "ongoing",
        "notes": "Primary Massachusetts regulatory authority.",
    },
    {
        "record_id": "ma_metrc_tracking_2025",
        "state": "MA",
        "domain": "tracking",
        "topic": "seed_to_sale",
        "title": "Massachusetts Metrc tracking partnership",
        "summary": "Massachusetts continued statewide cannabis track-and-trace operations through Metrc under a renewed contract announced in 2025.",
        "source_url": "https://www.metrc.com/news/metrc-extends-track-and-trace-partnership-through-new-contract-with-commonwealth-of-massachusetts/",
        "source_type": "tracking_vendor",
        "trust_level": "high",
        "keywords": ("metrc", "tracking", "massachusetts", "manifest", "inventory"),
        "update_cadence": "2025 contract",
        "notes": "Useful for seed-to-sale, manifests, and inventory traceability context.",
    },
    {
        "record_id": "ny_ocm_regulator",
        "state": "NY",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "New York Office of Cannabis Management",
        "summary": "Primary New York authority for adult-use, medical, and cannabinoid hemp licensing and guidance.",
        "source_url": "https://cannabis.ny.gov/",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("new york", "ocm", "license", "medical", "adult-use", "hemp"),
        "update_cadence": "ongoing",
        "notes": "Primary New York regulatory authority.",
    },
    {
        "record_id": "ny_plma_2025",
        "state": "NY",
        "domain": "compliance",
        "topic": "packaging_labeling_marketing",
        "title": "New York PLMA revised rules",
        "summary": "New York revised packaging, labeling, marketing, and advertising rules effective December 3, 2025, with some compliance deadlines extending to June 3, 2026.",
        "source_url": "https://cannabis.ny.gov/plma",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("plma", "packaging", "labeling", "marketing", "new york"),
        "update_cadence": "2025 rule update",
        "notes": "Critical for product launch, packaging, and retail compliance review.",
    },
    {
        "record_id": "nj_crc_regulator",
        "state": "NJ",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "New Jersey Cannabis Regulatory Commission",
        "summary": "Primary New Jersey regulator for medicinal and adult-use cannabis licensing, rules, and enforcement.",
        "source_url": "https://www.nj.gov/cannabis/",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("new jersey", "crc", "adult-use", "medical", "compliance"),
        "update_cadence": "ongoing",
        "notes": "Primary New Jersey compliance source.",
    },
    {
        "record_id": "nj_intoxicating_hemp_2026",
        "state": "NJ",
        "domain": "compliance",
        "topic": "intoxicating_hemp",
        "title": "New Jersey intoxicating hemp FAQ",
        "summary": "New Jersey's 2026 interim guidance explains thresholds, testing, age restrictions, and licensing implications for intoxicating hemp-derived products and beverages.",
        "source_url": "https://www.nj.gov/cannabis/resources/faqs/intoxicating-hemp/",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("hemp", "thc", "testing", "21", "beverages", "new jersey"),
        "update_cadence": "2026 interim guidance",
        "notes": "Useful for cannabinoid hemp, beverage, and THC-threshold decisions.",
    },
    {
        "record_id": "me_ocp_regulator",
        "state": "ME",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Maine Office of Cannabis Policy",
        "summary": "Primary Maine source for licensing, policy, compliance, and open data resources across adult-use and medical programs.",
        "source_url": "https://www.maine.gov/dafs/ocp/cannabis",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("maine", "ocp", "policy", "license", "compliance"),
        "update_cadence": "ongoing",
        "notes": "Primary Maine authority.",
    },
    {
        "record_id": "me_open_data_sales_testing",
        "state": "ME",
        "domain": "market",
        "topic": "open_data",
        "title": "Maine Cannabis Open Data portal",
        "summary": "Maine publishes open datasets for retail sales, compliance, testing, and licensee information for both adult-use and medical programs.",
        "source_url": "https://www.maine.gov/dafs/ocp/open-data",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("maine", "sales", "testing", "open data", "licensee", "compliance"),
        "update_cadence": "ongoing",
        "notes": "Strong source for market and testing trend context.",
    },
    {
        "record_id": "me_testing_requirements_2026",
        "state": "ME",
        "domain": "compliance",
        "topic": "mandatory_testing",
        "title": "Maine adult-use testing data and analyte categories",
        "summary": "Maine requires mandatory testing before sale and tracks failures across residual solvents, metals, yeasts/molds, microbes, pesticides, potency, homogeneity, and cannabinoid profiles.",
        "source_url": "https://www.maine.gov/dafs/ocp/open-data/adult-use/testing-data",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("testing", "residual solvents", "metals", "microbial", "pesticides", "homogeneity"),
        "update_cadence": "quarterly",
        "notes": "Useful for release readiness, contamination risk, and product-type failure trend context.",
    },
    {
        "record_id": "pa_medical_program",
        "state": "PA",
        "domain": "compliance",
        "topic": "medical_program",
        "title": "Pennsylvania Medical Marijuana Program",
        "summary": "Pennsylvania regulates cannabis through its medical marijuana program, including licensing, patient registry, and program oversight.",
        "source_url": "https://www.pa.gov/agencies/health/programs/medical-marijuana.html",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("pennsylvania", "medical", "patient", "program", "license"),
        "update_cadence": "ongoing",
        "notes": "Strong source for Pennsylvania medical program context.",
    },
    {
        "record_id": "mi_cra_regulator",
        "state": "MI",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Michigan Cannabis Regulatory Agency",
        "summary": "Michigan CRA oversees adult-use establishments, medical facilities, enforcement, social equity, hemp processing, and statewide marijuana monitoring resources.",
        "source_url": "https://www.michigan.gov/cra",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("michigan", "cra", "adult-use", "medical", "hemp", "enforcement"),
        "update_cadence": "ongoing",
        "notes": "Primary Michigan cannabis authority.",
    },
    {
        "record_id": "mi_adult_use_establishments",
        "state": "MI",
        "domain": "compliance",
        "topic": "adult_use_licensing",
        "title": "Michigan adult-use establishments",
        "summary": "Michigan CRA publishes adult-use licensing and rules resources for marijuana establishments under MRTMA and related administrative rules.",
        "source_url": "https://www.michigan.gov/cra/sections/adult-use",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("adult-use", "establishments", "mrtma", "rules", "licensing"),
        "update_cadence": "ongoing",
        "notes": "Useful for Michigan adult-use operational grounding.",
    },
    {
        "record_id": "md_cannabis_admin",
        "state": "MD",
        "domain": "compliance",
        "topic": "regulator_authority",
        "title": "Maryland Cannabis Administration",
        "summary": "Maryland Cannabis Administration provides consumer and program guidance covering licensed cultivation, manufacturing, testing, distribution, and retail activity.",
        "source_url": "https://cannabis.maryland.gov/pages/cannabisfaq.aspx",
        "source_type": "regulator",
        "trust_level": "high",
        "keywords": ("maryland", "cannabis administration", "testing", "distribution", "manufacturing"),
        "update_cadence": "ongoing",
        "notes": "Useful for Maryland program and consumer guidance context.",
    },
    {
        "record_id": "metrc_about",
        "state": null,
        "domain": "tracking",
        "topic": "traceability_platform",
        "title": "Metrc platform overview",
        "summary": "Metrc describes its RFID-enabled regulatory platform as delivering end-to-end supply-chain visibility across tracking, testing, transport, and sale.",
        "source_url": "https://www.metrc.com/about/",
        "source_type": "tracking_vendor",
        "trust_level": "medium",
        "keywords": ("metrc", "rfid", "traceability", "tracking", "transport", "testing"),
        "update_cadence": "ongoing",
        "notes": "Good background for seed-to-sale system capabilities.",
    },
    {
        "record_id": "scco2_selectivity_2022",
        "state": null,
        "domain": "extraction_science",
        "topic": "supercritical_co2_selectivity",
        "title": "Supercritical CO2 extraction selectivity and optimization",
        "summary": "Peer-reviewed work showed extraction yield and composition shift significantly with pressure and temperature, with low pressure favoring monoterpenes and higher pressure favoring cannabinoids like CBD.",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9502342/",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("supercritical co2", "pressure", "temperature", "terpenes", "cannabinoids", "selectivity"),
        "update_cadence": "stable",
        "notes": "Useful for terpene preservation and extraction-parameter reasoning.",
    },
    {
        "record_id": "scco2_fractionation_2022",
        "state": null,
        "domain": "extraction_science",
        "topic": "fractionation_strategy",
        "title": "SC-CO2 terpene-rich and CBD-rich fractionation study",
        "summary": "A systematic study found low pressures around 90–110 bar quickly recovered terpenes while higher pressures around 200–300 bar favored cannabidiol-rich fractions.",
        "source_url": "https://www.sciencedirect.com/science/article/pii/S0926669022008780",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("sc-co2", "fractionation", "terpene", "cbd", "pressure", "bar"),
        "update_cadence": "stable",
        "notes": "Useful when recommending pressure windows by target compound class.",
    },
    {
        "record_id": "decarb_review_2021",
        "state": null,
        "domain": "extraction_science",
        "topic": "decarboxylation",
        "title": "Acidic cannabinoid decarboxylation review",
        "summary": "Peer-reviewed review covering acidic-to-neutral cannabinoid conversion, kinetics, and how harvesting, storage, and processing influence decarboxylation.",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/34550791/",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("decarboxylation", "acidic cannabinoid", "thca", "cbda", "neutral cannabinoid"),
        "update_cadence": "stable",
        "notes": "Strong grounding for decarb warnings and conversion notes.",
    },
    {
        "record_id": "decarb_kinetics_2024",
        "state": null,
        "domain": "extraction_science",
        "topic": "decarboxylation_kinetics",
        "title": "Thermo-chemical conversion kinetics of cannabinoid acids",
        "summary": "Research on cannabinoid-acid conversion kinetics described temperature-dependent time-to-maximum concentration behavior for compounds such as CBD and CBG.",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/39080738/",
        "source_type": "peer_reviewed",
        "trust_level": "high",
        "keywords": ("thermo-chemical", "kinetics", "decarboxylation", "cbd", "cbg", "temperature"),
        "update_cadence": "stable",
        "notes": "Useful for time-temperature recommendations and over/under-conversion logic.",
    }
)
