REGULATION_LINKS = {
    "AL": {
        "program": "https://amcc.alabama.gov/",
        "statutes": "https://codes.findlaw.com/al/title-20-food-drugs-and-cosmetics/al-code-sect-20-2a-1/",
    },
    "AK": {"program": "https://www.commerce.alaska.gov/web/amco", "statutes": "https://www.akleg.gov/"},
    "AZ": {"program": "https://www.azdhs.gov/licensing/medical-marijuana/", "statutes": "https://www.azleg.gov/"},
    "AR": {"program": "https://www.dfa.arkansas.gov/medical-marijuana-commission/", "statutes": "https://www.arkleg.state.ar.us/"},
    "CA": {"program": "https://cannabis.ca.gov/", "statutes": "https://leginfo.legislature.ca.gov/"},
    "CO": {"program": "https://sbg.colorado.gov/marijuana-enforcement", "statutes": "https://leg.colorado.gov/"},
    "CT": {"program": "https://portal.ct.gov/cannabis", "statutes": "https://www.cga.ct.gov/"},
    "DE": {"program": "https://ocm.delaware.gov/", "statutes": "https://delcode.delaware.gov/"},
    "FL": {"program": "https://knowthefactsmmj.com/", "statutes": "https://www.leg.state.fl.us/"},
    "GA": {"program": "https://accessga.com/", "statutes": "https://www.legis.ga.gov/"},
    "HI": {"program": "https://health.hawaii.gov/medicalcannabis/", "statutes": "https://www.capitol.hawaii.gov/"},
    "ID": {"program": "https://legislature.idaho.gov/", "statutes": "https://legislature.idaho.gov/"},
    "IL": {"program": "https://idfpr.illinois.gov/profs/adultusecan.html", "statutes": "https://www.ilga.gov/"},
    "IN": {"program": "https://iga.in.gov/", "statutes": "https://iga.in.gov/"},
    "IA": {"program": "https://hhs.iowa.gov/omc", "statutes": "https://www.legis.iowa.gov/"},
    "KS": {"program": "https://www.kslegislature.gov/", "statutes": "https://www.kslegislature.gov/"},
    "KY": {"program": "https://kymedcan.ky.gov/", "statutes": "https://legislature.ky.gov/"},
    "LA": {"program": "https://ldh.la.gov/page/medical-marijuana", "statutes": "https://www.legis.la.gov/"},
    "ME": {"program": "https://www.maine.gov/dafs/ocp/cannabis", "statutes": "https://www.mainelegislature.org/"},
    "MD": {"program": "https://mmcc.maryland.gov/", "statutes": "https://mgaleg.maryland.gov/"},
    "MA": {"program": "https://masscannabiscontrol.com/", "statutes": "https://malegislature.gov/"},
    "MI": {"program": "https://www.michigan.gov/cra", "statutes": "https://www.legislature.mi.gov/"},
    "MN": {"program": "https://mn.gov/ocm/", "statutes": "https://www.revisor.mn.gov/"},
    "MS": {"program": "https://www.mmcp.ms.gov/", "statutes": "https://www.legislature.ms.gov/"},
    "MO": {"program": "https://health.mo.gov/safety/cannabis/", "statutes": "https://www.house.mo.gov/"},
    "MT": {"program": "https://mtrevenue.gov/cannabis/", "statutes": "https://leg.mt.gov/"},
    "NE": {"program": "https://nebraskalegislature.gov/", "statutes": "https://nebraskalegislature.gov/"},
    "NV": {"program": "https://ccb.nv.gov/", "statutes": "https://www.leg.state.nv.us/"},
    "NH": {"program": "https://www.dhhs.nh.gov/programs-services/population-health/therapeutic-cannabis-program", "statutes": "https://www.gencourt.state.nh.us/"},
    "NJ": {"program": "https://www.nj.gov/cannabis/", "statutes": "https://www.njleg.state.nj.us/"},
    "NM": {"program": "https://www.rld.nm.gov/cannabis/", "statutes": "https://www.nmlegis.gov/"},
    "NY": {"program": "https://cannabis.ny.gov/", "statutes": "https://www.nysenate.gov/"},
    "NC": {"program": "https://www.ncleg.gov/", "statutes": "https://www.ncleg.gov/"},
    "ND": {"program": "https://www.hhs.nd.gov/health/medical-marijuana", "statutes": "https://ndlegis.gov/"},
    "OH": {"program": "https://com.ohio.gov/divisions-and-programs/cannabis-control", "statutes": "https://codes.ohio.gov/"},
    "OK": {"program": "https://oklahoma.gov/omma.html", "statutes": "https://www.oscn.net/"},
    "OR": {"program": "https://www.oregon.gov/olcc/marijuana/", "statutes": "https://www.oregonlegislature.gov/"},
    "PA": {"program": "https://www.pa.gov/agencies/health/programs/medical-marijuana.html", "statutes": "https://www.legis.state.pa.us/"},
    "RI": {"program": "https://cannabis.ri.gov/", "statutes": "https://webserver.rilegislature.gov/"},
    "SC": {"program": "https://www.scstatehouse.gov/", "statutes": "https://www.scstatehouse.gov/"},
    "SD": {"program": "https://medTHC.sd.gov/", "statutes": "https://sdlegislature.gov/"},
    "TN": {"program": "https://www.capitol.tn.gov/", "statutes": "https://www.capitol.tn.gov/"},
    "TX": {"program": "https://www.dps.texas.gov/section/compassionate-use-program", "statutes": "https://statutes.capitol.texas.gov/"},
    "UT": {"program": "https://medicalcannabis.utah.gov/", "statutes": "https://le.utah.gov/"},
    "VT": {"program": "https://ccb.vermont.gov/", "statutes": "https://legislature.vermont.gov/"},
    "VA": {"program": "https://www.cca.virginia.gov/", "statutes": "https://law.lis.virginia.gov/"},
    "WA": {"program": "https://lcb.wa.gov/marj", "statutes": "https://app.leg.wa.gov/"},
    "WV": {"program": "https://omc.wv.gov/", "statutes": "https://code.wvlegislature.gov/"},
    "WI": {"program": "https://docs.legis.wisconsin.gov/", "statutes": "https://docs.legis.wisconsin.gov/"},
    "WY": {"program": "https://wyoleg.gov/", "statutes": "https://wyoleg.gov/"},
    "DC": {"program": "https://abca.dc.gov/page/medical-cannabis-program", "statutes": "https://code.dccouncil.gov/"},
}
